language: java
jdk:
    - oraclejdk8
node_js: "0.10"
addons:
    postgresql: "9.4"

before_script:
  - pip install --user codecov

script:
  - mvn clean verify -Pintegration-test
  - ./ui-test.sh

after_success:
  - codecov

# go faster on travis
# fuckoff fast, I want same behaviour on every branch
sudo: true
