language: java
jdk:
    - oraclejdk8
addons:
    postgresql: "9.4"

script:
  - mvn clean verify -Pintegration-test

after_success:
  - mvn clean test jacoco:report coveralls:report

# go faster on travis
sudo: false
