language: java
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8
addons:
    postgresql: "9.3"

script: mvn clean package

after_success:
  - mvn jacoco:report coveralls:report

# go faster on travis
sudo: false
