zmon:
  oauth2:
    sso:
      client-id: YourGitHubClientID
      client-secret: YourGitHubClientSecret
  signup:
    github:
      # Specify users who are authorized to log in
      # Empty list allows all users to log in
      allowed-users: ['*']
      # Specify organizations who are authorized to log in
      allowed-orgas: ['*']
  authorities:
    simple:
      admins: []
      users: []
  teams:
    simple:
      teams:
        jbellmann:
          - firstTeam
          - secondTeam
          - thirdTeam
