zmon:
  oauth2:
    sso:
      client-id: d843ddae9fe32bdaab6c
      client-secret: 31ef34a9fa0542ec2ac743a4a81962a71483d5c1
  signup:
    github:
      # Specify users who are authorized to log in
      # Empty list allows all users to log in
      allowed-users: ['*']
      # Specify organizations who are authorized to log in
      allowed-orgas: ['*']
  authorities:
    simple:
      admins: []
      users: []
  teams:
    simple:
      teams:
        jbellmann:
          - firstTeam
          - secondTeam
          - thirdTeam
